CREATE TABLE DEMO (
id NUMBER,
description VARCHAR(200)
);

SELECT * FROM DEMO;

INSERT INTO DEMO VALUES('','Testing1');

SET UPDATE DEMO id = '1' WHERE description = 1;


-- Quizioner
/*
1. Tampilkan orders
dengan nama, address, website, credit_limit dari customer dengan first_name, email, phone, job_title dari employees

2. Tampilkan orders,
dengan product_name, description dari producst dengan category_name dari product_categories.

*/


SELECT X.ORDER_ID "ID", Y.NAME "NAMA", Y.ADDRESS "ALAMAT", Y.WEBSITE "WEBSITE", Y.CREDIT_LIMIT "LIMIT KREDIT", Z.FIRST_NAME "NAMA DEPAN EMPLOYEE", Z.EMAIL "EMAIL", Z.PHONE "NOMOR HP", Z.JOB_TITLE "POSISI JABATAN"
FROM (ORDERS X JOIN CUSTOMERS Y ON X.CUSTOMER_ID = Y.CUSTOMER_ID) JOIN EMPLOYEES Z ON X.SALESMAN_ID = Z.EMPLOYEE_ID
WHERE X.ORDER_ID = '39';

-- ORDERS, PRODUCT, PRODUCT CATEGORIES
SELECT X.ORDER_ID "ID", Y.PRODUCT_NAME "PRODUCT NAME", Y.DESCRIPTION "DESKRIPSI", Z.CATEGORY_NAME "NAMA KATEGORI"
FROM (ORDERS X JOIN ORDER_ITEMS O ON X.ORDER_ID = O.ORDER_ID )JOIN PRODUCTS Y ON O.PRODUCT_ID = Y.PRODUCT_ID
JOIN PRODUCT_CATEGORIES Z ON Y.CATEGORY_ID = Z.CATEGORY_ID
WHERE X.ORDER_ID = '39';    


-- Group Function

SELECT * FROM PRODUCTS;

SELECT MAX(LIST_PRICE) FROM PRODUCTS;

SELECT * FROM PRODUCTS
WHERE LIST_PRICE = (SELECT MAX(LIST_PRICE) FROM PRODUCTS);

SELECT ORDER_ITEMS.ORDER_ID, (SELECT ORDERS.ORDER_DATE FROM ORDERS WHERE ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID)
FROM ORDER_ITEMS;

SELECT
P.PRODUCT_ID AS ID,
P.PRODUCT_NAME AS NAME,
SUM(OI.QUANTITY) AS SOLD
FROM PRODUCTS P
JOIN ORDER_ITEMS OI ON P.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME;

SELECT PRODUCTS.PRODUCT_ID, PRODUCTS.PRODUCT_NAME, 
(SELECT SUM(ORDER_ITEMS.QUANTITY) FROM ORDER_ITEMS
WHERE ORDER_ITEMS.PRODUCT_ID = PRODUCTS.PRODUCT_ID) "QTY"
FROM PRODUCTS
ORDER BY PRODUCT_ID ASC;