-- PROCEDURE 1
CREATE OR REPLACE PROCEDURE COBA1 AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('TEST');
    DBMS_OUTPUT.PUT_LINE('TEST');
END COBA1;

-- menjalankan prosedur
exec COBA1;


-- PROCEDURE 2
CREATE OR REPLACE PROCEDURE COBA2
(
    NAMA IN VARCHAR2
) AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello');
    DBMS_OUTPUT.PUT_LINE(NAMA);
END COBA2;


-- PROCEDURE 3
CREATE OR REPLACE PROCEDURE COBA3
(
    PARAM1 IN NUMBER,
    PARAM2 IN NUMBER
) AS
BEGIN
DECLARE
    A NUMBER := 0;
BEGIN
    A := PARAM1+PARAM2;
    DBMS_OUTPUT.PUT_LINE(A);
END;
END COBA3;

EXEC COBA3(3,4);


-- PROCEDURE 4
CREATE OR REPLACE PROCEDURE COBA4
(
    PARAM1 IN NUMBER
) AS
    X SYS_REFCURSOR;
BEGIN
    OPEN X FOR 
    SELECT customer_id, name
    FROM customers
    WHERE customer_id = PARAM1;
    
    dbms_sql.return_result(X);
END COBA4;

exec COBA4(39);

-- PROCEDURE 5
CREATE OR REPLACE PROCEDURE COBA5
(
    PARAM1 IN NUMBER
) AS
--    X SYS_REFCURSOR;
    Y customers.customer_id%type;
    Z customers.name%TYPE;
BEGIN
--    OPEN X FOR 
    SELECT customer_id, name into Y,Z
    FROM customers
    WHERE customer_id = PARAM1;
    
    dbms_output.put_line(Y);
    dbms_output.put_line(Z);
END COBA5;

exec COBA5(39);

-- Function
CREATE OR REPLACE FUNCTION FUNCTION1 
(
  PARAM1 IN VARCHAR2 
) RETURN VARCHAR2 AS 
BEGIN
  RETURN PARAM1;
END FUNCTION1;

-- FUNCTION 2
CREATE OR REPLACE FUNCTION FUNCTIONCOBA2 
(
  PARAM1 IN NUMBER 
, PARAM2 IN NUMBER 
) RETURN VARCHAR2 AS 
BEGIN
  RETURN PARAM1 + PARAM2;
END FUNCTIONCOBA2;

-- FUNCTION 3
CREATE OR REPLACE FUNCTION FUNCTIONCOBA3 
(
  PARAM1 IN NUMBER 
) RETURN VARCHAR2 AS
    Y customers.customer_id%TYPE;
    Z customers.name%TYPE;
BEGIN
    SELECT customer_id, name into y,z
    FROM customers
    WHERE customer_id = PARAM1;
    
  RETURN Y || ' ' || Z;
END FUNCTIONCOBA3;

SET SERVEROUTPUT ON;
DECLARE
BEGIN
COBA5(39);
COBA3(2,3);
DBMS_OUTPUT.PUT_LINE(function1('Aditya'));
DBMS_OUTPUT.PUT_LINE(functioncoba2(2,3));
END;

